[package]
name = "fanboy"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "2.1.0"
lazy_static = "1.5.0"
libm = "0.2.11"
proc_mem = "0.1.6"
wgpu = "24.0.0"
winapi = "0.3.0"
windows = { version = "0.59.0", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging", "Win32_System_LibraryLoader", "Win32_System"] }

